name: VerificationPR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: âš¡ï¸ build swift codes
        run: swift build

      - name: ğŸ§ª run test codes
        run: swift test
      
      - name: âœ¨ lint
        run: swiftlint
        
      - name: â˜‘ï¸ check make
        run: make --dry-run > /dev/null
    
      - name: â˜‘ï¸ check tuist
        run: make tuist-build
